  name: CI
  on:
    push:
      branches: [ master ]
  jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
        - name: get repo
          uses: actions/checkout@v4
          with:
            fetch-depth: 2
        - name: get path of main.py
          run: |
            echo "zero_length_string=\"\"" >> $GITHUB_ENV
            echo "path_of_main_py=$(git diff --name-only HEAD~1 HEAD | grep '/main\.py')" >> $GITHUB_ENV
            echo $path_of_main_py
            echo ${{ env.path_of_main_py }}
            echo "path_of_main_py=$path_of_main_py\"\"" >> $GITHUB_ENV
            echo $path_of_main_py
            echo ${{ env.path_of_main_py }}
        - name: Check main.py exists
          run: |
            if [${{ env.zero_length_string }} == ${{ env.path_of_main_py }}]; then
              echo "No main.py"
              exit 1
            fi
        - name: Decorate path_of_main_py
          run: echo "path_of_main_py=https://github.com/skysign/WSAPT/${{ env.path_of_main_py }}" >> $GITHUB_ENV
        - name: Print path_of_main_py
          run: echo "${{ env.path_of_main_py }}"
