  name: CI
  on:
    push:
      branches: [ master ]
  jobs:
    job1:
      runs-on: ubuntu-latest
      outputs:
        output1: ${{ steps.step1.outputs }}
      steps:
        - uses: actions/checkout@v3      
          with: 
            fetch-depth: 1
        - id: step1
          run: git diff --name-only HEAD~1 HEAD | grep '/main.py'
    job2:
      needs: job1    
      runs-on: ubuntu-latest	
      steps:
        - env:
            output1: ${{needs.job1.outputs.output1}}
          run: echo "$output1"
